import { Contact, Project } from "@/features/publicInvolvement/piTool/types";

export let projectsData: Project[] = [
  {
    number: "00-000",
    name: "Highway 89 Expansion",
    client: "UDOT Region 1",
    startDate: "2024-01-01",
    endDate: "2025-01-01",
  },
  {
    number: "00-001",
    name: "I-15 Bridge Repair",
    client: "UDOT Region 2",
    startDate: "2024-03-15",
    endDate: "2024-11-30",
  },
  {
    number: "00-002",
    name: "US-6 Safety Improvements",
    client: "UDOT Region 3",
    startDate: "2024-05-01",
    endDate: "2025-09-30",
  },
  {
    number: "00-003",
    name: "SR-201 Resurfacing",
    client: "UDOT Region 2",
    startDate: "2024-07-01",
    endDate: "2024-10-31",
  },
  {
    number: "00-004",
    name: "I-80 Wildlife Crossing",
    client: "UDOT Region 1",
    startDate: "2024-09-01",
    endDate: "2025-08-31",
  },
  {
    number: "01-005",
    name: "US-40 Intersection Upgrade",
    client: "UDOT Region 3",
    startDate: "2024-04-15",
    endDate: "2024-12-15",
  },
];

export let contactsData: Contact[] = [
  {
    id: 1,
    firstName: "Dan",
    lastName: "Kimball",
    email: "dkimball@avenueconsutlants.com",
    phone: "801-656-9255",
    projects: [
      "I-80 Wildlife Crossing",
      "US-6 Safety Improvements",
      "US-40 Intersection Upgrade",
      "Highway 89 Expansion",
    ],
  },
  {
    id: 2,
    firstName: "John",
    lastName: "Doe",
    email: "jdoe@example.com",
    phone: "123-456-7890",
    projects: ["I-80 Wildlife Crossing", "Highway 89 Expansion"],
  },
  {
    id: 3,
    firstName: "Jane",
    lastName: "Smith",
    email: "jsmith@example.com",
    phone: "234-567-8901",
    projects: ["Highway 89 Expansion"],
  },
  {
    id: 4,
    firstName: "Michael",
    lastName: "Johnson",
    email: "mjohnson@example.com",
    phone: "345-678-9012",
    projects: ["I-80 Wildlife Crossing", "US-6 Safety Improvements"],
  },
  {
    id: 5,
    firstName: "Emily",
    lastName: "Davis",
    email: "edavis@example.com",
    phone: "456-789-0123",
    projects: ["US-40 Intersection Upgrade"],
  },
  {
    id: 6,
    firstName: "David",
    lastName: "Brown",
    email: "dbrown@example.com",
    phone: "567-890-1234",
    projects: ["Highway 89 Expansion"],
  },
  {
    id: 7,
    firstName: "Sarah",
    lastName: "Miller",
    email: "smiller@example.com",
    phone: "678-901-2345",
    projects: [],
  },
  {
    id: 8,
    firstName: "James",
    lastName: "Wilson",
    email: "jwilson@example.com",
    phone: "789-012-3456",
    projects: [],
  },
  {
    id: 9,
    firstName: "Laura",
    lastName: "Moore",
    email: "lmoore@example.com",
    phone: "890-123-4567",
    projects: [],
  },
  {
    id: 10,
    firstName: "Robert",
    lastName: "Taylor",
    email: "rtaylor@example.com",
    phone: "901-234-5678",
    projects: [],
  },
  {
    id: 11,
    firstName: "Linda",
    lastName: "Anderson",
    email: "landerson@example.com",
    phone: "012-345-6789",
    projects: [],
  },
  {
    id: 12,
    firstName: "Christopher",
    lastName: "Thomas",
    email: "cthomas@example.com",
    phone: "123-456-7891",
    projects: [],
  },
  {
    id: 13,
    firstName: "Patricia",
    lastName: "Jackson",
    email: "pjackson@example.com",
    phone: "234-567-8902",
    projects: [],
  },
  {
    id: 14,
    firstName: "Matthew",
    lastName: "White",
    email: "mwhite@example.com",
    phone: "345-678-9013",
    projects: [],
  },
  {
    id: 15,
    firstName: "Barbara",
    lastName: "Harris",
    email: "bharris@example.com",
    phone: "456-789-0124",
    projects: [],
  },
  {
    id: 16,
    firstName: "Joshua",
    lastName: "Martin",
    email: "jmartin@example.com",
    phone: "567-890-1235",
    projects: [],
  },
  {
    id: 17,
    firstName: "Karen",
    lastName: "Thompson",
    email: "kthompson@example.com",
    phone: "678-901-2346",
    projects: [],
  },
];
